<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Call to undefined function {method} on the cursor' => '',
  'EMongoCache.connectionID "{id}" is invalid. Please make sure it refers to the ID of a EMongoClient application component.' => '',
  'EMongoSession.connectionID "{id}" is invalid. Please make sure it refers to the ID of a EMongoClient application component.' => '',
  'MongoDB Active Record requires a "mongodb" EMongoClient application component.' => '',
  'Set an incorrect primary key.' => '',
  'The "db" application component must be configured to be a EMongoClient object.' => '',
  'The MongoCursor must have a model' => '',
  'The active record cannot be deleted because it is new.' => '',
  'The active record cannot be inserted to database because it is not new.' => '',
  'The active record cannot be updated because it has primary key set.' => '',
  'The active record cannot be updated because it is new.' => '',
  'The active record cannot be updated because its _id is not set!' => '',
  'You must supply a subdocument type of either "many" or "one" in order to validate subdocuments' => '',
  'You must supply either some rules to validate by or a class name to use' => '',
  'You need to set a collection first in order to execute mongodb operations' => '',
  '{attribute} "{value}" has already been taken.' => '',
  '{attribute} "{value}" is invalid.' => '',
  '{class} does not have relation "{name}".' => '',
  '{class} has an invalid validation rule. The rule must specify attributes to be validated and the validator name.' => '',
);
