<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Already member' => 'Ya tengo cuenta',
  'Sign up' => 'Registrate',
  'Your email' => 'Tu email',
  'Your email is mandatory' => 'Tu email es obligatorio',
  'Your first name' => 'Tu nombre',
  'Your first name is mandatory' => 'Tu nombre es obligatorio',
  'Your last name' => 'Tus apellidos',
  'Your last name is mandatory' => 'Tus apellidos son obligatorios',
  'Your password' => 'Tu contaseña',
  'Your password is mandatory' => 'Tu contraseña es obligatoria',
  'Your username' => 'Tu usuario',
  'Your username is mandatory' => 'Tu usuario es obligatorio',
  'Hi! Please fill all the fields to create your account.' => '¡Hola! Rellena todos los campos para crear tu cuenta.',
);
